site_name: Chippy Documentation
site_url: https://rohkud.github.io/chippy/

theme:
  name: material
  features:
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Using Chippy as a Dependency: using-packages.md
  - Publishing to GitHub Packages: publishing-github-packages.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rohkud/chippy
      name: View on GitHub
