site_name: Chippy Documentation
site_url: https://rohkud.github.io/chippy/

theme:
  name: material
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started: getting-started.md
